[logging]
level = "debug"

[neo4j]
uri="neo4j://127.0.0.1:7687"
user="neo4j"
password="password"

[ledger]
reader_user="all_reader_user"
parties=[
    "Bob::12202a7f4e8ec4dd77132209767e53c4c383338deab5ff7b5dffd263173dcc3820ad",
  "Alice::12202a7f4e8ec4dd77132209767e53c4c383338deab5ff7b5dffd263173dcc3820ad"]
url="http://localhost:6865"