[logging]
level = "debug"

[neo4j]
uri="neo4j://127.0.0.1:7687"
user="neo4j"
password="password"

[ledger]
reader_user="all_reader_user"
parties=[
  "Alice::1220b156f64bdba326f6b822c0d43111452eefd28b91de5d2658009eb532e602055e",
  "Bob::1220b156f64bdba326f6b822c0d43111452eefd28b91de5d2658009eb532e602055e",]
url="http://localhost:6865"