[logging]
level = "debug"

[neo4j]
uri="neo4j://127.0.0.1:7687"
user="neo4j"
password="password"

[ledger]
reader_user="all_reader_user"
parties=[
  "Alice::1220b235f1ec22f48b1305b6fb7590c76e48d97145e133a5f4906c83fd276946ca54",
  "Bob::1220b235f1ec22f48b1305b6fb7590c76e48d97145e133a5f4906c83fd276946ca54"]
url="http://localhost:6865"