[logging]
level = "debug"

[neo4j]
uri="neo4j://127.0.0.1:7687"
user="neo4j"
password="password"

[ledger]
reader_user="all_reader_user"
parties=[
    "Alice::1220a3fefa628fda3ef2dc36486d85b7d30859f07931578552dfe8c002298e636827",
  "TicketWizard::1220a3fefa628fda3ef2dc36486d85b7d30859f07931578552dfe8c002298e636827",
  "ScroogeBank::1220a3fefa628fda3ef2dc36486d85b7d30859f07931578552dfe8c002298e636827"]
url="http://localhost:6865"