[logging]
level = "debug"

[neo4j]
uri="neo4j://127.0.0.1:7687"
user="neo4j"
password="password"

[ledger]
fake_jwt_user="alice"
parties=[
  "Bob::12202a795d567e4faf0a1e7750e58a3ad51af4a5e15da97edc16c47d82b1d10c62b3",
  "Alice::12202a795d567e4faf0a1e7750e58a3ad51af4a5e15da97edc16c47d82b1d10c62b3"]
url="http://localhost:6865"