[logging]
level = "debug"

[neo4j]
uri="neo4j://127.0.0.1:7687"
user="neo4j"
password="password"

[ledger]
reader_user="all_reader_user"
parties=[
  "Bob::12207b6abe0d7ee9dd84969bdd3690e59c25bae13a810d336259a139e2d30c3d6381",
  "Alice::12207b6abe0d7ee9dd84969bdd3690e59c25bae13a810d336259a139e2d30c3d6381"]
url="http://localhost:6865"